#!/usr/bin/env bash
# ============================================================
#  Generate version header for C++ and config for PlatformIO
#  Called by the Makefile before building each component.
#
#  Usage:
#    ./scripts/gen-version.sh               # prints version string
#    ./scripts/gen-version.sh --cpp <out>    # generate C++ header
#    ./scripts/gen-version.sh --pio <out>    # generate PlatformIO build flags
#    ./scripts/gen-version.sh --gradle       # print version for Gradle
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$ROOT_DIR/VERSION"

# Read version
source "$VERSION_FILE"

# Git info (if available)
GIT_HASH="unknown"
GIT_DIRTY=""
if command -v git &>/dev/null && git -C "$ROOT_DIR" rev-parse HEAD &>/dev/null; then
    GIT_HASH=$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    if ! git -C "$ROOT_DIR" diff --quiet 2>/dev/null; then
        GIT_DIRTY="-dirty"
    fi
fi

VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
if [ -n "$VERSION_TAG" ]; then
    case "$VERSION_TAG" in
        .*|-*) VERSION_FULL="${VERSION}${VERSION_TAG}" ;;
        *)     VERSION_FULL="${VERSION}-${VERSION_TAG}" ;;
    esac
else
    VERSION_FULL="${VERSION}"
fi
BUILD_STR="${VERSION_FULL}+${GIT_HASH}${GIT_DIRTY}"

MODE="${1:-}"

case "$MODE" in
    --cpp)
        OUTFILE="${2:-/dev/stdout}"
        cat > "$OUTFILE" << HEADER
// Auto-generated by gen-version.sh — do not edit
#pragma once

#define OGUN_VERSION_MAJOR  ${VERSION_MAJOR}
#define OGUN_VERSION_MINOR  ${VERSION_MINOR}
#define OGUN_VERSION_PATCH  ${VERSION_PATCH}
#define OGUN_VERSION        "${VERSION_FULL}"
#define OGUN_BUILD          "${BUILD_STR}"
#define OGUN_GIT_HASH       "${GIT_HASH}${GIT_DIRTY}"
HEADER
        ;;
    --pio)
        # Output build flags for platformio.ini extra_build_flags
        OUTFILE="${2:-/dev/stdout}"
        cat > "$OUTFILE" << FLAGS
; Auto-generated by gen-version.sh — do not edit
-DOGUN_VERSION_MAJOR=${VERSION_MAJOR}
-DOGUN_VERSION_MINOR=${VERSION_MINOR}
-DOGUN_VERSION_PATCH=${VERSION_PATCH}
-DOGUN_VERSION='"${VERSION_FULL}"'
-DOGUN_BUILD='"${BUILD_STR}"'
FLAGS
        ;;
    --gradle)
        echo "$VERSION"
        ;;
    *)
        echo "$BUILD_STR"
        ;;
esac
